# import libraries

In [25]:
import pandas as pd

# import data

In [26]:
df = pd.read_csv("./salaries.csv")
df.head()
df.shape
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

# Perliminary Data cleaning

In [27]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

# Finding the Major with Highest Starting Salary

In [28]:
max_id = clean_df['Starting Median Salary'].idxmax()
max_major = clean_df['Undergraduate Major'].loc[max_id]
print(max_major)

Physician Assistant

# Finding the Major with Highest Median Salary

In [29]:
max_id = clean_df['Mid-Career Median Salary'].idxmax()
max_major = clean_df.loc[max_id]
print(max_major)

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object


# Finding the Major with Lowest Starting Salary

In [30]:
max_id = clean_df['Starting Median Salary'].idxmin()
max_major = clean_df.loc[max_id]
print(max_major)

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

# Finding the Major with Lowest Median Salary

In [31]:
max_id = clean_df['Mid-Career Median Salary'].idxmin()
max_major = clean_df.loc[max_id]
print(max_major)

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

# Calculation Spread

In [32]:
spread = abs(clean_df['Mid-Career 10th Percentile Salary'] - clean_df['Mid-Career 90th Percentile Salary'])
clean_df.insert(1 , 'Spread' , spread)

In [ ]:
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

# Low risk majors

In [34]:
low_risk = clean_df.sort_values('Spread').head(5)

In [35]:
print(low_risk)

           Undergraduate Major   Spread  Starting Median Salary  \
40                     Nursing  50700.0                 54200.0
43         Physician Assistant  57600.0                 74300.0
41                   Nutrition  65300.0                 39900.0
49                     Spanish  65400.0                 34000.0
27  Health Care Administration  66400.0                 38800.0

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
40                   67000.0                            47600.0
43                   91700.0                            66400.0
41                   55300.0                            33900.0
49                   53100.0                            31000.0
27                   60600.0                            34600.0

    Mid-Career 90th Percentile Salary     Group
40                            98300.0  Business
43                           124000.0      STEM
41                            99200.0      HASS
49                            96400.0      HASS
27                           101000.0  Business

# Jobs with highest potential

In [37]:
high_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False).head(5)

In [38]:
print(high_potential)

     Undergraduate Major    Spread  Starting Median Salary  \
17             Economics  159400.0                 50100.0
22               Finance  147800.0                 47900.0
8   Chemical Engineering  122100.0                 63200.0
37                  Math  137800.0                 45400.0
44               Physics  122000.0                 50300.0

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
17                   98600.0                            50600.0
22                   88300.0                            47200.0
8                   107000.0                            71900.0
37                   92400.0                            45200.0
44                   97300.0                            56000.0

    Mid-Career 90th Percentile Salary     Group
17                           210000.0  Business
22                           195000.0  Business
8                            194000.0      STEM
37                           183000.0      STEM
44                           178000.0      STEM

# Highest Risk Jobs

In [39]:
high_risk = clean_df.sort_values('Spread', ascending=False).head(5)

In [40]:
print(high_risk)

   Undergraduate Major    Spread  Starting Median Salary  \
17           Economics  159400.0                 50100.0
22             Finance  147800.0                 47900.0
37                Math  137800.0                 45400.0
36           Marketing  132900.0                 40800.0
42          Philosophy  132500.0                 39900.0

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
17                   98600.0                            50600.0
22                   88300.0                            47200.0
37                   92400.0                            45200.0
36                   79600.0                            42100.0
42                   81200.0                            35500.0

    Mid-Career 90th Percentile Salary     Group
17                           210000.0  Business
22                           195000.0  Business
37                           183000.0      STEM
36                           175000.0  Business
42                           168000.0      HASS

# Grouping by most Group

In [42]:
most_group = clean_df.groupby('Group').count()

In [43]:
print(most_group)

          Undergraduate Major  Spread  Starting Median Salary  \
Group
Business                   12      12                      12
HASS                       22      22                      22
STEM                       16      16                      16

          Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
Group
Business                        12                                 12
HASS                            22                                 22
STEM                            16                                 16

          Mid-Career 90th Percentile Salary
Group
Business                                 12
HASS                                     22
STEM                                     16

# mean salary by group

In [54]:
groups = list(clean_df['Group'].unique())

In [ ]:
print(groups)

['Business', 'STEM', 'HASS']

In [58]:
# getting mean salary per group
mean_salaries = {}
for group in groups:
    mean_salaries[group] = float(clean_df[clean_df['Group']==group]['Mid-Career Median Salary'].mean())

In [61]:
mean_df = clean_df.groupby('Group').mean(numeric_only=True)
print(mean_df)

                 Spread  Starting Median Salary  Mid-Career Median Salary  \
Group
Business  103958.333333            44633.333333              75083.333333
HASS       95218.181818            37186.363636              62968.181818
STEM      101600.000000            53862.500000              90812.500000

          Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary
Group
Business                       43566.666667                      147525.000000
HASS                           34145.454545                      129363.636364
STEM                           56025.000000                      157625.000000

In [59]:
print(mean_salaries)

{'Business': 75083.33333333333, 'STEM': 90812.5, 'HASS': 62968.181818181816}